In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Dindori_updated_Q_RF.xlsx')
df.drop(columns = [ 'Grid No.', 'Grid Name', 'LAT', 'LONG', 'Weights', 'Q(t-1)' ], inplace = True)
df.drop(columns = ['Q(t-2)', 'Q(t-3)', 'Q(t-4)', 'Q(t-5)', 'Q(t-6)', 'Q(t-7)', 'Q(t-8)', 'Q(t-9)', 'Q(t-10)', 'Q(t-11)', 'Q(t-12)', 'Q(t-13)', 'Q(t-14)', 'Q(t-15)'], inplace = True)
df

,Dates,Year,Month,Day,RF_Grid 1,RF_Grid 2,RF_Grid 3,RF_Grid 5,RF_Grid 6,RF_Grid 7,RF_Grid 8,RF_Grid 9,RF_Grid 10,RF_Grid 11,LRF,Q
0,1988-08-01,1988,8,1,90.9,64.7,25.5,69.4,86.8,41.5,26.1,65.6,81.3,50.3,133.964576,793.60
1,1988-08-02,1988,8,2,5.0,3.6,5.6,78.2,14.3,2.8,1.8,90.9,6.5,5.5,17.501768,2649.00
2,1988-08-03,1988,8,3,9.0,10.7,9.3,30.2,25.0,12.4,8.5,30.4,23.3,29.4,24.230551,155.60
3,1988-08-04,1988,8,4,57.0,42.2,47.4,54.6,40.4,33.9,31.9,56.0,42.3,47.0,94.523243,428.00
4,1988-08-05,1988,8,5,9.7,7.9,6.4,6.1,16.1,5.5,1.7,3.2,16.0,8.2,14.759911,115.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10826,2020-09-17,2020,9,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.094996,88.64
10827,2020-09-23,2020,9,23,44.5,50.9,50.9,44.2,44.4,49.5,60.9,42.1,41.8,42.8,93.554305,244.26
10828,2020-09-26,2020,9,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043000,104.64
10829,2020-10-05,2020,10,5,2.6,3.2,11.8,2.4,0.7,0.6,2.6,1.7,0.9,0.9,4.516504,83.43
10830,2020-10-14,2020,10,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043000,82.79

In [3]:
k = 3
j = 0
rows_to_drop = []

for i in range(0, 29):
    if k == i:
        rows_to_drop.extend(range(61 + 365*i + j, 305 + 365*i + j))
        k = k + 4
        j = j + 1
    elif k != i:
        rows_to_drop.extend(range(61 + 365*i + j, 305 + 365*i + j - 1))

rows_to_drop.extend(range(10689, 10831))
# Drop all the rows in one go
df.drop(rows_to_drop, inplace=True)
df

,Dates,Year,Month,Day,RF_Grid 1,RF_Grid 2,RF_Grid 3,RF_Grid 5,RF_Grid 6,RF_Grid 7,RF_Grid 8,RF_Grid 9,RF_Grid 10,RF_Grid 11,LRF,Q
0,1988-08-01,1988,8,1,90.9,64.7,25.5,69.4,86.8,41.5,26.1,65.6,81.3,50.3,133.964576,793.600000
1,1988-08-02,1988,8,2,5.0,3.6,5.6,78.2,14.3,2.8,1.8,90.9,6.5,5.5,17.501768,2649.000000
2,1988-08-03,1988,8,3,9.0,10.7,9.3,30.2,25.0,12.4,8.5,30.4,23.3,29.4,24.230551,155.600000
3,1988-08-04,1988,8,4,57.0,42.2,47.4,54.6,40.4,33.9,31.9,56.0,42.3,47.0,94.523243,428.000000
4,1988-08-05,1988,8,5,9.7,7.9,6.4,6.1,16.1,5.5,1.7,3.2,16.0,8.2,14.759911,115.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10684,2018-09-26,2018,9,26,0.0,0.5,2.3,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.238863,19.550000
10685,2018-09-27,2018,9,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043000,21.460000
10686,2018-09-28,2018,9,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043000,19.220000
10687,2018-09-29,2018,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043000,16.066667
10688,2018-09-30,2018,9,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043000,15.278333

In [4]:
df.to_excel('Monsoon.xlsx')