In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Gadarwara_Q.xlsx')
df.drop(columns = ['Dates', 'Year','Month', 'Day', 'Unnamed: 18', 'Grid Point','weights'], inplace = True)
df

,RF_1,RF_2,RF_3,RF_4,RF_5,RF_6,RF_7,RF_8,RF_10,LRF,Q,Q(t-1),Q(t-2),Q(t-3)
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.60,0.00,0.00,0.00
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.60,1.60,0.00,0.00
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.60,1.60,1.60,0.00
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.60,1.60,1.60,1.60
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.60,1.60,1.60,1.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.08,0.09,0.10,0.11
15702,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.07,0.08,0.09,0.10
15703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.05,0.07,0.08,0.09
15704,1.1,0.3,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.099727,0.05,0.05,0.07,0.08
15705,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.05,0.05,0.05,0.07

In [3]:
corr = df.corr()
corr

,RF_1,RF_2,RF_3,RF_4,RF_5,RF_6,RF_7,RF_8,RF_10,LRF,Q,Q(t-1),Q(t-2),Q(t-3)
RF_1,1.000000,0.828524,0.804047,0.679937,0.863207,0.690999,0.407513,0.792614,0.671287,0.730137,0.480762,0.243458,0.128583,0.123851
RF_2,0.828524,1.000000,0.724498,0.649186,0.778977,0.675435,0.424543,0.891566,0.702380,0.725673,0.510026,0.279469,0.144043,0.136724
RF_3,0.804047,0.724498,1.000000,0.953363,0.889592,0.844599,0.511462,0.738198,0.743063,0.869750,0.526067,0.265201,0.151568,0.150742
RF_4,0.679937,0.649186,0.953363,1.000000,0.829102,0.879928,0.677190,0.673147,0.758416,0.932836,0.517155,0.257824,0.153816,0.150889
RF_5,0.863207,0.778977,0.889592,0.829102,1.000000,0.922067,0.495851,0.808851,0.813567,0.847811,0.548052,0.274331,0.157831,0.143594
RF_6,0.690999,0.675435,0.844599,0.879928,0.922067,1.000000,0.698658,0.733903,0.872741,0.926427,0.543083,0.272167,0.161669,0.144542
RF_7,0.407513,0.424543,0.511462,0.677190,0.495851,0.698658,1.000000,0.429230,0.627017,0.847834,0.356916,0.172349,0.105498,0.096334
RF_8,0.792614,0.891566,0.738198,0.673147,0.808851,0.733903,0.429230,1.000000,0.801115,0.757565,0.539130,0.289136,0.163791,0.149337
RF_10,0.671287,0.702380,0.743063,0.758416,0.813567,0.872741,0.627017,0.801115,1.000000,0.842958,0.528193,0.289660,0.182199,0.161400
LRF,0.730137,0.725673,0.869750,0.932836,0.847811,0.926427,0.847834,0.757565,0.842958,1.000000,0.541027,0.271386,0.159932,0.149965
Q,0.480762,0.510026,0.526067,0.517155,0.548052,0.543083,0.356916,0.539130,0.528193,0.541027,1.000000,0.434633,0.327407,0.302694
Q(t-1),0.243458,0.279469,0.265201,0.257824,0.274331,0.272167,0.172349,0.289136,0.289660,0.271386,0.434633,1.000000,0.434633,0.327407
Q(t-2),0.128583,0.144043,0.151568,0.153816,0.157831,0.161669,0.105498,0.163791,0.182199,0.159932,0.327407,0.434633,1.000000,0.434633
Q(t-3),0.123851,0.136724,0.150742,0.150889,0.143594,0.144542,0.096334,0.149337,0.161400,0.149965,0.302694,0.327407,0.434633,1.000000

In [4]:
corr.to_excel('Gadarwara_correlation_python.xlsx')